- buildSrc/src/main/java/Repositories.kt
The "password" terminology was used before because the old CI used it.
There is no preferences on the new Github Action, so now, we match the
Bintray's terminology: "key"
JIRA: EE-1164
> Fix development of Bintray artifacts

- .github/workflows/release.yml
- buildSrc/src/main/java/Slack.kt
- buildSrc/src/main/java/azure/AzureBlobStorage.kt
The new deployment workflow use the GitHub releases as a trigger. For 
the moment, creating the release is a manual step (consisting of 
copy/paste of info in the slack notif). We could try to work later on it
to make the release fully automated.
JIRA: EE-1166
> Add a pipeline for deploying production releases

- buildSrc/src/main/java/Publications.kt
Github does not handle HTTP requests. In browser, it is automatically
redirected to HTTPS. But Bintray does not seem to handle the
redirection, the HTTPS link should be provided.
JIRA: EE-1167
> Fix Github URL declared to Bintray

- CHANGELOG.md
- buildSrc/src/main/java/Slack.kt
This is to avoid having publisher looking at the changelog and expecting
features/bugs in a version that is not yet released.
> Move in progress changes in a dedicated section of the CHANGELOG.md

- .github/workflows/release.yml
- buildSrc/src/main/java/azure/AzureBlobStorage.kt
It was deactivated to test the new deploy pipeline.
This also fix the Slack notification by providing the webhook.
JIRA: EE-1166
> Reactivate Azure deployment

- .github/workflows/main.yml
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/CriteoInterstitialActivityTest.java
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/advancednative/AdvancedNativeFunctionalTest.java
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/csm/CsmFunctionalTest.java
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/integration/CriteoFunctionalTest.java
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/integration/MoPubHeaderBiddingFunctionalTest.java
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/interstitial/InterstitialActivityHelperTest.java
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/network/PubSdkApiIntegrationTest.java
- publisher-sdk/src/main/java/com/criteo/publisher/csm/MetricObjectQueueFactory.java
In parallel of Java tests, instrumentation tests should be run on a
single emulator. If emulator crashes, logcat should be available as a
temporary build artifact. If test fails, test report should be available
as a temporary build artifact
As this is totally new, some tests are expected to fail. Easy-to-fix tests might be fixed. Others might be ignored for now a fixed later in EE-1180.
JIRA: EE-1165
> Run instrumentation tests in Github Action and prepare tests to be run

- app/build.gradle.kts
- buildSrc/src/main/java/Repositories.kt
JCenter only accept packages representing library with .jar or .aar
The test app is not in this case, and there is no meaning to sync it on
JCenter anyway. Hence, we push it on Bintray but in a dedicated package.
So the SDK and the test utils can be sync with JCenter.
This also remove the declaration of the specific Bintray repo of Criteo.
As mediation adapters are now sync with JCenter, this is not needed
anymore.
JIRA: EE-1167
> Deploy the test app in a dedicated package on Bintray

- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/CriteoInterstitialActivityTest.java
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/csm/CsmFunctionalTest.java
Android tests were never run on CI before. Hence, it is expected to find
some flakyness in tests. Such flaky tests are first deactivated. We will
try later to fix them in EE-1180.
> Deactivate some flaky tests

- test-utils/src/main/java/com/criteo/publisher/view/WebViewClicker.java
The mopub adapter needed to duplicate and improve itself those utilities when adding functional tests (see https://github.com/criteo/android-publisher-sdk-mopub-adapters/pull/10).
Those duplication and improvement are moved here, in the test-utils module.
> Improve utility methods on webview for the mopub adapter

- .github/workflows/main.yml
The Gradle files does not change that much. When there is no change, the
gradle cache is cached between runs on the CI. It is expected that this
speed up the build time.
It would also be nice to cache the Android SDK because this can take a while. But the action we're currently using does not seem to fully accept recycle SDK when (https://github.com/Malinskiy/action-android/issues/26).
> Store cache between CI runs

- .github/workflows/main.yml
This is to handle PR and version branches such as v3.8.0.
> Trigger tests for all PR

- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/csm/CsmFunctionalTest.java
- test-utils/src/main/java/com/criteo/publisher/mock/CdbMock.kt
- test-utils/src/main/java/com/criteo/publisher/mock/MockedDependenciesRule.java
The logcat shows that, even by setting a really small timeout threshold,
timeout are not always throws by the network layer. This may be due
because the CDB mock server is embedded and fast.
In order to stabilize, the test, in addition of the small timeout
threshold, the CBB mock server is also throttled.
> Stabilize CSM test about timeout network

- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/csm/CsmFunctionalTest.java
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/integration/ProfileIdFunctionalTest.kt
- test-utils/src/main/java/com/criteo/publisher/csm/MetricHelper.kt
- test-utils/src/main/java/com/criteo/publisher/mock/ApplicationMock.java
- test-utils/src/main/java/com/criteo/publisher/mock/MockedDependenciesRule.java
- Given SDK used for the first time
- When initializing the SDK with ad units in prefetch
- And waiting for idle state
- Then CDB call is done with fallback profile ID
- Given initialized SDK
- Given bid response fetched for InHouse (or any other integration)
- Given SDK rebooted (in-memory data is flush)
- When initializing the SDK with ad units in prefetch
- And waiting for idle state
- Then CDB call is done with InHouse (or other) profile ID
- Given SDK used for the first time
- When initializing the SDK
- And waiting for idle state
- Then remote config call is done with fallback profile ID
- Given initialized SDK
- Given bid response fetched for InHouse (or any other integration)
- Given SDK rebooted (in-memory data is flush)
- When initializing the SDK
- And waiting for idle state
- …
> Add E2E tests on Profile ID

- .github/workflows/main.yml
This GA is now using "main" as default branch. Using the master one
yield this warning:
The "master" branch is no longer the default branch name for
actions/upload-artifact
Please pin to a specific version or use "main".
To stay out of any change a fixed version is used instead.
> Use fixed version for the upload-artifact GA

- CHANGELOG.md
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/headerbidding/MoPubHeaderBiddingTest.java
- publisher-sdk/src/main/java/com/criteo/publisher/headerbidding/MoPubHeaderBidding.java
- publisher-sdk/src/main/java/com/criteo/publisher/util/ReflectionUtil.java
On Android header bidding integrations, we check the class name to decide the integration type and properly insert keywords by using string equality, e.g. "MoPubView" / "MoPubInterstitial" for MoPub.
Some publishers may extend these classes and use subclasses of GAM / MoPub objects, currently we can't set keywords with these subclasses.
We'd like to support both the original MoPub objects and their subclasses.
JIRA: EE-1113
> Handle subclasses of MoPub objects

- buildSrc/src/main/java/Slack.kt
This block is not really helpful for public release.
> Hide Git block in Slack notif on public release

- .github/workflows/main.yml
- app/src/main/AndroidManifest.xml
- buildSrc/build.gradle.kts
- buildSrc/src/main/java/Deps.kt
- publisher-sdk-tests/build.gradle.kts
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/CriteoInterstitialActivityTest.java
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/activity/TopActivityFinderTest.java
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/advancednative/AdChoiceOverlayTest.java
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/advancednative/VisibilityCheckerTest.java
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/csm/CsmFunctionalTest.java
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/integration/CriteoFunctionalTest.java
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/integration/DfpHeaderBiddingFunctionalTest.java
- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/integration/StandaloneFunctionalTest.java
- publisher-sdk-tests/src/main/AndroidManifest.xml
This will retry failing tests up to 3 times. This plugin wrap the
connected Android tests and its main features are:
- Retrying failing tests
- Generating JUnit XML reports (with syserr for recovered flaky tests)
- Generating HTML reports with failing/recovering/passing tests
- Printing ongoing tests in stdout without --info on Gradle logger
Why do we need it ?
Because your tests are so flaky that the devs have to use Head&Shoulders
dandruff shampoo</Gordon Ramsay>
> Setup Gordon Gradle plugin to retry failing tests

- publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/integration/StandaloneFunctionalTest.java
The assertions from AssertJ are verbose in case of failure: tested
objects and criteria are displayed in the failure messages giving a good
hint.
The replacement of JUnit assertions is particularly made on this class
because tests are really flaky and may even fail on the CI after 5
retries.
> Improve observability of test by using AssertJ

- .github/workflows/main.yml
- CONTRIBUTING.md
- test-utils/build.gradle.kts
On merge, all tests are run, but only flaky ones are retried.
Only tests declared as flaky are run with a retry policy. Other tests
are always run normally.
This prevents any true negative to pass the tests.
Also, the Gordon runner does not support Jacoco coverage. So only flaky
tests are not counted in the coverage report. Which is a good thing,
because we cannot affirm that something is really covered if the tests
are flaky.
Moreover, runners with retry policies, such as Gordon, are slow compared
to the default test runner. This would speed up the CI on merge.
> Fix tests and coverages on merge

- build.gradle.kts
For those reports, Sonar is expecting paths to directories containing
files reports rather than the path to the files themselves.
> Fix path of JUnit reports given to Sonar

- .github/workflows/main.yml
When developing on a branch, this will provide test and quality reports
like on main branch.
Moreover, Sonar needs the base branch to be analysed to produce correct
analysis. For instance, current PR on the v4.0.0 are getting bad Sonar
reports because v4.0.0 is still unknown to it.
> Run CI on version branches

- publisher-sdk/src/androidTest/java/com/criteo/publisher/BearcatPrivacyFunctionalTest.java
This test is a little bit flaky and the assertion shows that the GAID is
null. Log has been setup on AdvertisingInfo class to find the cause. It
appears that the Google API may throw IOException sometimes:
```
[ 08-21 16:59:09.235  5120:12828 D/AdvertisingInfo ]
java.io.IOException: Interrupted exception
at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source:25)
at com.google.android.gms.ads.identifier.AdvertisingIdClient.zza(Unknown Source:25)
at com.google.android.gms.ads.identifier.AdvertisingIdClient.getAdvertisingIdInfo(Unknown Source:47)
at com.criteo.publisher.util.AdvertisingInfo$SafeAdvertisingIdClient.isLimitAdTrackingEnabled(AdvertisingInfo.java:80)
at com.criteo.publisher.util.AdvertisingInfo.isLimitAdTrackingEnabled(AdvertisingInfo.java:60)
at …
```
> Accept nullable value for GAID in test

- publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/StandaloneFunctionalTest.java
The "whenLoadingAnInterstitial GivenBidAvailable*" in Standalone
tests is very very flaky and makes the build fail even after 5 retries.
Like on #74 (23e29ea), the test waits for the webview to be ready before
reading the HTML.
> Add synchronization on flaky test again

- publisher-sdk/src/androidTest/java/com/criteo/publisher/network/PubSdkApiIntegrationTest.java
- test-utils/src/main/java/com/criteo/publisher/mock/CdbMock.kt
The stub vs preprod tests are failing because of couple diffs:
- Zone ID is always 0 on the preprod
- TTL is always 3600
Constants are used to reduce work in case of update.
> Resynchronize CDB stub with preprod

- publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/StandaloneFunctionalTest.java
The test was expecting two callbacks from the old interstitial
listeners: `onAdReceived` and `onAdReadyToDisplay`. With the merge of
the listeners, there is now only one callback fired when the
interstitial is ready to be displayed.
Note that this was not caught by CI, because during PR, only
deterministic tests are run, and flaky tests, such as this one, are only
run at merge, which is only activated recently on version branches.
> Fix functional tests after merging interstitial listeners

- .github/workflows/main.yml
Currently we have two warnings on Sonar reports:
```
Could not find ref 'main' in refs/heads, refs/remotes/upstream or
refs/remotes/origin. You may see unexpected issues and changes. Please
make sure to fetch this ref before pull request analysis.
```
and
```
Shallow clone detected during the analysis. Some files will miss SCM
information. This will affect features like auto-assignment of issues.
Please configure your build to disable shallow clone.
```
The first one seems to be the origin of wrong coverage rate and issues
reported in PRs.
The second one indicates that we're missing the auto-assignment of
issues because only the last commit was fetched.
By fetching the whole Git history, the warnings are solved, improving
the reporting on PR and introducing a new feature for free.
> Fetch the whole Git history when running Sonar

- CHANGELOG.md
- buildSrc/src/main/java/SdkVersion.kt
The bump is done now, ahead of time to avoid polluting 3.9.0 artifacts
with breaking changes from the v4.0.0.
> Bump version to 4.0.0

- CHANGELOG.md
The changelog extractor is defined to search sections containing the
text `# Version $version`.
> Fix declaration of version 3.10.0 in CHANGELOG.md

- publisher-sdk/src/main/java/com/criteo/publisher/CriteoBannerEventController.java
- publisher-sdk/src/main/java/com/criteo/publisher/CriteoBannerView.java
- publisher-sdk/src/main/java/com/criteo/publisher/CriteoInterstitial.java
- publisher-sdk/src/main/java/com/criteo/publisher/CriteoInterstitialEventController.java
- publisher-sdk/src/test/java/com/criteo/publisher/CriteoBannerViewTest.java
- publisher-sdk/src/test/java/com/criteo/publisher/CriteoInterstitialTest.java
While semantically, the ad has already loaded before displaying it, we
still want to distinguish between success and failure cases (invalid
display data for example).
> Trigger onAdReceived for server-side bidding

- publisher-sdk/src/main/java/com/criteo/publisher/Criteo.java
- publisher-sdk/src/main/java/com/criteo/publisher/CriteoInternal.java
- publisher-sdk/src/main/java/com/criteo/publisher/CriteoInterstitial.java
- publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java
- publisher-sdk/src/test/java/com/criteo/publisher/CriteoInterstitialTest.java
- publisher-sdk/src/test/java/com/criteo/publisher/CriteoTest.java
Problem:
When an error happens during the initialization path, Criteo instance
will be `null` and any future call to Criteo.getInstance() will throw a
RuntimeException.
Solution:
DummyCriteo is assigned to Criteo singleton object, when any runtime
exception is thrown during initialization. While the integration will
not work, it will prevent the host application from crashing. Logging
will allow us to investigate and correct the root cause with the
publisher.
-----
Guard against null application in CriteoInterstitial
Problem:
An `application` object is required for the SDK to operate properly.
However, nothing prevents CriteoInterstitialActivity from being open even if
`application` is null.
Solution:
CriteoInterstitial APIs must check wehther `application` is null or
return immediately. …
> Use DummyCriteo if not initialized properly

- test-utils/build.gradle.kts
- test-utils/src/androidTest/java/com/criteo/publisher/mock/DependenciesAnnotationInjectionAndroidTest.kt
- test-utils/src/androidTest/java/com/criteo/publisher/mock/JavaDummyDependencyProvider.java
- test-utils/src/main/java/com/criteo/publisher/mock/DependenciesAnnotationInjection.java
As we're moving forward on Java 8 feature, lambdas will appear in the
dependency provider. Currently the DependenciesAnnotationInjection does
not handled method generated by Android compiler when a lambda is
capturing `this`.
This is fixed by ignoring synthetic methods. Synthetic elements are the
elements added by a Java compiler but without any trace in the source
code. Hence it is legitimate to ignore such methods.
> Support dependency provider with lambda capturing "this"

- README.md
Some publishers have mistaken the test app in this repository as the sample app for integrations. Adding a link to the sample repository in Readme would be useful to lead them to the right sample.
> Add a link to sample project repository in Readme

- publisher-sdk/src/main/java/com/criteo/publisher/BidResponseListener.java
- publisher-sdk/src/main/java/com/criteo/publisher/model/AdUnit.kt
`AdUnit` is used during SDK init:
```
public Builder adUnits(@Nullable List<AdUnit> adUnits);
```
So it should stay public for publishers.
> Keep AdUnit interface unmangled and not internal

- CHANGELOG.md
- app/src/main/java/com/criteo/testapp/InHouseActivity.java
- app/src/main/java/com/criteo/testapp/StandaloneActivity.java
- app/src/main/java/com/criteo/testapp/StandaloneRecyclerViewActivity.kt
- app/src/main/java/com/criteo/testapp/listener/TestAppBannerAdListener.java
- app/src/main/java/com/criteo/testapp/listener/TestAppNativeAdListener.java
- app/src/main/res/layout/activity_in_house.xml
- app/src/main/res/layout/activity_stand_alone.xml
- publisher-sdk-tests/src/main/res/layout/test_criteo_banner_view_illegal_1.xml
- publisher-sdk-tests/src/main/res/layout/test_criteo_banner_view_illegal_2.xml
- publisher-sdk-tests/src/main/res/layout/test_criteo_banner_view_illegal_3.xml
- publisher-sdk-tests/src/main/res/layout/test_criteo_banner_view_inhouse.xml
- publisher-sdk-tests/src/main/res/layout/test_criteo_banner_view_standalone.xml
- publisher-sdk-tests/src/main/res/values/attrs.xml
- publisher-sdk/src/androidTest/java/com/criteo/publisher/CriteoBannerViewTest.java
- publisher-sdk/src/main/java/com/criteo/publisher/CriteoBannerView.java
- publisher-sdk/src/main/java/com/criteo/publisher/CriteoInternal.java
- publisher-sdk/src/main/java/com/criteo/publisher/logging/Logger.java
- publisher-sdk/src/main/res/values/attrs.xml
- publisher-sdk/src/test/java/com/criteo/publisher/logging/LoggerTest.kt
In order to use `CriteoBannerView`, publishers have to instantiate it by
hand and add it to a parent layout programmatically. This is both
inefficient as it creates an unnecessary depth in the view tree, and
tedious.
By turning `CriteoBannerView` into a custom view, publishers will be
able to define it in the layout XML file directly.
> Make CriteoBannerView a custom view class

- .github/workflows/main.yml
- app/build.gradle.kts
- app/src/main/java/com/criteo/testapp/MopubMediationActivity.java
The `check` command only executes tests. For Java plugin, the `build`
one executes `check` and `assemble`. For Android, the sources are
conflicting.
So CI is executing both assemble+build commands.
Sources:
- https://proandroiddev.com/understanding-gradle-the-build-lifecycle-5118c1da613f
- https://docs.gradle.org/current/userguide/java_plugin.html
> Use Gradle build command to validate library+Fix CI

- app/src/main/java/com/criteo/testapp/ServerBiddingActivity.kt
An UninitializedPropertyAccessException was thrown when activity is
destroyed without displaying the banner.
> Fix crash when destroying server bidding activity

- gradle.properties
Sometime, CI is failing because of:
```
A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> java.lang.ExceptionInInitializerError (no error message)
```
As this is a false negative, a common solution is to increase the max
memory allocation pool of Gradle.
> Fix Gradle unstable by increasing Xmx

- app/src/main/java/com/criteo/testapp/listener/TestAppInterstitialAdListener.java
Memory leak caused by the following reference chain:
CriteoResultReceiver -> .. ->  TestAppInterstitialAdListener -> AppCompatButton  -> StandaloneActivity
> Fix memory leak in test app

- app/src/main/java/com/criteo/testapp/InHouseActivity.java
- app/src/main/java/com/criteo/testapp/StandaloneActivity.java
- app/src/main/java/com/criteo/testapp/listener/TestAppInterstitialAdListener.java
- app/src/main/res/layout/activity_stand_alone.xml
For Standalone and InHouse, before there was a distinction between:
- valid bid is received
- ad payload is received
To show this distinction, the bid was requested when the activity was
resumed. If valid bid is received, then a button is enabled. Testers had
to click on the button to display the Ad.
This distinction is removed: listener is notified when valid bid is
received AND ad payload is received. The testing process is
simplified to:
- Button is always enabled
- (Manual) Tester clicks on the button
- Bid is requested
- If bid is valid, then ad payload is requested
- If ad payload is received, then interstitial is shown
- (Manual) Tester checks quality of the Ad
> Simplify loading of interstitials in test app

- app/build.gradle.kts
When running `./gradlew connectedCheck`, the following error was
triggered:
More than one file was found with OS independent path 'META-INF/mediation_release.kotlin_module'
Excluding this file is safe.
> Make connectedCheck work again

- .github/workflows/main.yml
- .github/workflows/release.yml
Two of the actions that we use: action-android, and
junit-report-annotations-action use the deprecated set-env command. As a
result, CI was failing.
This change includes a temporary workaround.
These workarounds will be removed, once:
- malinskiy/action-android is updated to not use set-env.
- We create a fork or contribute to junit-report-annotations-action.
> Fix CI failures

- buildSrc/src/main/java/AndroidModule.kt
The Android JUnit runner is sniffing some data when we run our tests.
The worse part is that sometimes the network connection is bad (I can't
tell if it was an issue client side or server side) and, after tests are
really finished, the tests process takes many seconds to stop.
> Disable analytics sent to Google when running tests

- publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/CriteoFunctionalTest.java
This test is broken because of 2aa15017: AsyncTack of AppEvent is
replaced by Executor+Runnable. With AsyncTask, only a single GUM request
can be executed at the same time. With Executor, many GUM requests can
be done in parallel.
With new solution, it appears that two events are sent when starting a
new activity: Launch then Active events.
The former approach is tedious and not deterministic because if network
is slow, then only the "Launch" event is sent, if network is fast, then
both events are sent.
So test is updated to accept the two events. The @FlakyTest is also
removed on this test:
- the new solution is deterministic
- recent work was done to isolate tests, particularly on AppEvents
> Fix functional test on AppEvent

- publisher-sdk/src/main/java/com/criteo/publisher/logging/ConsoleHandler.kt
- publisher-sdk/src/main/java/com/criteo/publisher/logging/LogTag.kt
- publisher-sdk/src/main/java/com/criteo/publisher/logging/Logger.java
- publisher-sdk/src/main/java/com/criteo/publisher/network/PubSdkApi.java
- publisher-sdk/src/test/java/com/criteo/publisher/logging/LogTagTest.kt
- publisher-sdk/src/test/java/com/criteo/publisher/network/PubSdkApiTest.java
* Use gdpr_consent instead of gdprString for GUM
Although this is not consistent with all the other keys,
PTag already uses this key and the idea was to align with
IAB standard.
* Use CriteoSdk instead of Crto as log tags
> Tag change (CriteoSdk) + GUM gdpr param key (#169)

- .github/workflows/main.yml
- .github/workflows/release.yml
- build.gradle.kts
This new version solves the deprecated `set-env`.
JIRA: EE-1365
> Bump version of malinskiy's GitHub actions

- publisher-sdk/src/androidTest/java/com/criteo/publisher/advancednative/AdvancedNativeFunctionalTest.java
- publisher-sdk/src/androidTest/java/com/criteo/publisher/util/AdvertisingInfoTest.kt
- publisher-sdk/src/main/java/com/criteo/publisher/CriteoInternal.java
- publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java
- publisher-sdk/src/main/java/com/criteo/publisher/util/AdvertisingInfo.java
- publisher-sdk/src/test/java/com/criteo/publisher/CriteoInternalUnitTest.java
- publisher-sdk/src/test/java/com/criteo/publisher/util/AdvertisingInfoNoIdentifierTest.kt
The Google API is throwing an exception when called on the main thread:
```
java.lang.IllegalStateException: Calling this from your main thread can lead to deadlock
```
The GAID is fetched in 4 cases:
- when creating the CDB request
- when creating the Bearcat request
- when creating the remote config request
- when creating the remote logs request
The 3 first cases are done on worker thread and current solution is ok.
The remote log case can be done on any thread, including the main one
which is problematic.
To solve this issue we can either:
1. run remote log handler/logger in a (dedicated?) worker thread
2. refactor AdvertisingInfo class to have an async API (listener/future)
3. make AdvertisingInfo callable from any thread
Pros:
- slow logger cannot impact business
- no change needed …
> Make AdvertisingInfo callable on any thread

- publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/MoPubHeaderBiddingFunctionalTest.java
AppBidding declaration is delayed when bid is consumed. For live
bidding, it is 100% sure that good profile ID is only visible on next
bid request.
For cache bidding, then it depends on the threads scheduling. Such tests
are now flaky, this means that a previous commit did change the
scheduling.
The commit 94ddc4d7 is a good candidate as it is recent and change main
thread usage. For cache bidding, we have:
- valid bid is retrieved from cache (test thread)
- bid is consumed (main thread)
- MoPub profile ID is declared (main thread) (1)
- bid is fetched for cache (worker thread)
- GAID is fetched for bid request (worker thread) (2)
- Profile ID is fetched for bid request (worker thread) (3)
- ...
(1) and (3) are concurrent events, and without synchronization, there is
no deterministic …
> Fix flaky MoPub tests

- publisher-sdk/src/androidTest/java/com/criteo/publisher/CriteoInterstitialActivityTest.java
The assertion is loosen by accepting `onAdClosed` to be called.
JIRA: EE-1191
> Fix interstitial test

- publisher-sdk/src/main/java/com/criteo/publisher/SdkInitLogMessage.kt
Log level is downgrade to INFO. Log indicates to dismiss the message if
using mediation adapter (which are calling Criteo#init multiple times)
> Rephrase log emitted when publisher called SDK init twice

- publisher-sdk/src/main/java/com/criteo/publisher/logging/RemoteLogRecordsFactory.kt
- publisher-sdk/src/test/java/com/criteo/publisher/logging/RemoteLogRecordsFactoryTest.kt
Remote logs are bulk. So each chunk has the same server time. To be able
to reorder the logs, the client date time is included in the message.
Before, time was printed only down to seconds which is a too big unit of
time. So it was almost impossible to use it.
This commit shows the milliseconds too, so one can distinguish the real
log order.
Maybe for later:
Even with millis, logs might not be fully reorder. An atomic log IDs
could be used instead.
> Show millis of client date time when generating remote logs

- publisher-sdk/src/androidTest/java/com/criteo/publisher/BidManagerFunctionalTest.java
- publisher-sdk/src/androidTest/java/com/criteo/publisher/csm/CsmFunctionalTest.java
- publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/ProfileIdFunctionalTest.kt
- publisher-sdk/src/main/java/com/criteo/publisher/BidManager.java
- publisher-sdk/src/main/java/com/criteo/publisher/CdbCallListener.kt
- publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java
- publisher-sdk/src/main/java/com/criteo/publisher/LiveCdbCallListener.java
- publisher-sdk/src/main/java/com/criteo/publisher/csm/CsmBidLifecycleListener.java
- publisher-sdk/src/main/java/com/criteo/publisher/csm/MetricSendingQueueProducer.java
- publisher-sdk/src/main/java/com/criteo/publisher/model/CdbResponse.java
- publisher-sdk/src/main/java/com/criteo/publisher/privacy/ConsentData.kt
- publisher-sdk/src/test/java/com/criteo/publisher/LiveCdbCallListenerTests.kt
- publisher-sdk/src/test/java/com/criteo/publisher/csm/CsmBidLifecycleListenerTest.kt
- publisher-sdk/src/test/java/com/criteo/publisher/model/CdbResponseTest.java
- test-utils/src/main/java/com/criteo/publisher/network/CdbMock.kt
The consent verification is made prior to sending metrics in the sending queue (in other words: what get puts into the sending queue, will be sent).
There are three states:
- CONSENT_GIVEN
- CONSENT_NOT_GIVEN
- CONSENT_UNKNOWN (when the response isn't retrieved from the backend yet).
When we are in the last state, we still write metrics. But, `CONSENT_GIVEN` is mandatory to send metrics to the sending queue.
> Send CSM data only if consent is given

- publisher-sdk/src/main/java/com/criteo/publisher/privacy/ConsentData.kt
This will avoid unnecessary contention. `apply` is an atomic operation, but writing 
involves grabbing the reference to the `editor` first. Therefore, the only effect is that 
reading might not return the latest available value, but that is an acceptable trade-off.
> Remove the synchronization in ConsentData

- test-utils/src/main/java/com/criteo/publisher/network/CdbMock.kt
The integration tests are checking that CDB mock produce the same output
than the preprod. They are current failing because the tests are
comparing the raw results without knowing the format (JSON).
> Fix IT by moving consentGiven field in CDB mock response

- test-utils/src/main/java/com/criteo/publisher/network/CdbMock.kt
This was tested locally to avoid to do another fix commit.
> Fix IT by removing quotes around consentGiven value of CDB mock

- publisher-sdk/src/androidTest/java/com/criteo/publisher/logging/RemoteLoggingFunctionalTest.kt
- publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java
- publisher-sdk/src/main/java/com/criteo/publisher/logging/RemoteLogRecords.kt
- publisher-sdk/src/main/java/com/criteo/publisher/logging/RemoteLogSendingQueueConsumer.kt
- publisher-sdk/src/test/java/com/criteo/publisher/logging/RemoteLogSendingQueueConsumerTest.kt
- test-utils/src/main/java/com/criteo/publisher/csm/ConcurrentSendingQueueHelper.java
- test-utils/src/main/java/com/criteo/publisher/mock/MockedDependenciesRule.java
Such situation might happen when the log record was created on the main
thread and that the deviceId was not ready yet: for instance for logs
emitted during initialization of the SDK.
The deviceId is assumed to be a constant. Hence, it is not an issue to
set it later. Although, this is quite a workaround based on an
assumption. Hence, the deviceId is kept if it is already set.
JIRA: EE-1411
> Inject deviceId when missing in persisted log records

- publisher-sdk/src/main/java/com/criteo/publisher/SafeRunnable.java
- publisher-sdk/src/main/java/com/criteo/publisher/logging/RemoteLogRecords.kt
- publisher-sdk/src/test/java/com/criteo/publisher/SafeRunnableTest.kt
In release artifacts, the enum element was mangled, and even with the
`@SerializedName`, the GSON library still needs to access to enum values
by reflection.
JIRA: EE-1412
> Fix serialization of RemoteLogLevel

- publisher-sdk/src/main/java/com/criteo/publisher/util/JsonSerializer.java
UTF-8 is generally the default encoding on Android. But it might not be
always the case. For instance, on Windows, the NativeProductTest is
failing without the explicit UTF-8 encoding.
> Explicitly use UTF-8 to write/read JSON

- buildSrc/src/main/java/AndroidModule.kt
There was some accumulation of deprecated API that might be fixed in
order to bump the API level.
For the moment, no error is triggered.
> Display deprecations when building the SDK

- CHANGELOG.md
- publisher-sdk/build.gradle.kts
- publisher-sdk/config.groovy
- publisher-sdk/consumer-proguard.txt
- publisher-sdk/src/main/java/com/criteo/publisher/csm/MetricSendingQueueConfiguration.kt
- publisher-sdk/src/main/java/com/criteo/publisher/csm/SendingQueueConfiguration.kt
- publisher-sdk/src/main/java/com/criteo/publisher/csm/SendingQueueFactory.java
- publisher-sdk/src/main/java/com/criteo/publisher/csm/TapeSendingQueue.java
- publisher-sdk/src/main/java/com/criteo/publisher/logging/RemoteHandler.kt
- publisher-sdk/src/main/java/com/criteo/publisher/logging/RemoteLogSendingQueueConfiguration.kt
- publisher-sdk/src/main/java/com/criteo/publisher/util/BuildConfigWrapper.java
- publisher-sdk/src/test/java/com/criteo/publisher/csm/TapeSendingQueueTest.kt
- publisher-sdk/src/test/java/com/criteo/publisher/logging/RemoteHandlerTest.kt
The `TapeSendingQueue` class accesses private members of a the
com.squareup.tape dependency:
- `FileObjectQueue#queueFile`
- `QueueFile#usedBytes()`
This privates members are used to determine the real size, in bytes, of
the queue. Then the queue can be capped to avoid consuming too much
memory (disk).
When using this SDK, publishers can apply minification. Since AGP 3.4.0,
R8 is enabled by default. Before Proguard was used. It is still possible
to used Proguard by applying `android.enableRB=false` in the
`gradle.properties`, but this option is deprecated since AGP 3.6.0.
With R8 minification, there is no error to signal.
With Proguard minification and optimization enabled, it is possible to
produce an infinite loop of `NoSuchMethodException` logs.
The explanation is that, with the …
> Fix infinite loop of NoSuchMethodException

- publisher-sdk/src/main/java/com/criteo/publisher/CriteoInterstitialActivity.java
From documentation: This value cannot be null.
See: https://developer.android.com/reference/android/webkit/WebView#setWebViewClient(android.webkit.WebViewClient)
> Stop setting a null webview client

- .github/workflows/main.yml
Playstore emulators are more flaky than google_apis ones
> 🔧 Use only google_apis emulators for CI
