.github/workflows/main.yml, publisher-sdk-tests/build.gradle.kts
=> Use a GitHub Action to report JUnit errors as annotation

.github/workflows/main.yml
=> Add a postsubmit-like job in Github Action

CHANGELOG.md, app/src/main/java/com/criteo/pubsdk_android/TestAppNativeRenderer.java, app/src/main/res/layout/native_ad.xml, publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/advancednative/AdvancedNativeFunctionalTest.java, publisher-sdk-tests/src/main/java/com/criteo/publisher/activity/TestNativeActivity.java, publisher-sdk/src/main/java/com/criteo/publisher/advancednative/CriteoNativeAd.java, publisher-sdk/src/test/java/com/criteo/publisher/advancednative/NativeAdMapperTest.kt
=> Add long legal text on Advanced Native

app/src/main/AndroidManifest.xml, buildSrc/src/main/java/Deps.kt, publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/integration/MoPubHeaderBiddingFunctionalTest.java, publisher-sdk-tests/src/main/AndroidManifest.xml
=> Update MoPub dependency to 5.13.1

publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/integration/DfpHeaderBiddingFunctionalTest.java
This will add some context which would help us understand why dfp tests
fail on GitHub Actions.
=> Log DFP failedToLoad error in tests

publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/headerbidding/MoPubHeaderBiddingTest.java, publisher-sdk/src/main/java/com/criteo/publisher/headerbidding/DfpHeaderBidding.java, publisher-sdk/src/main/java/com/criteo/publisher/headerbidding/HeaderBidding.java, publisher-sdk/src/main/java/com/criteo/publisher/headerbidding/HeaderBiddingHandler.java, publisher-sdk/src/main/java/com/criteo/publisher/headerbidding/MoPubHeaderBidding.java, publisher-sdk/src/main/java/com/criteo/publisher/headerbidding/OtherAdServersHeaderBidding.java, publisher-sdk/src/test/java/com/criteo/publisher/headerbidding/HeaderBiddingTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/headerbidding/OtherAdServersHeaderBiddingTest.kt
=> Clean Bids for Auto-Refreshing Banners

CHANGELOG.md
=> Indicate in CHANGELOG that MoPub Auto-Refresh is supported

publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/BidManagerFunctionalTest.java, publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/advancednative/AdvancedNativeFunctionalTest.java, publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/csm/CsmFunctionalTest.java, publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/integration/DfpHeaderBiddingFunctionalTest.java, publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/integration/InHouseFunctionalTest.java, publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/integration/MoPubHeaderBiddingFunctionalTest.java, publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/integration/StandaloneFunctionalTest.java, publisher-sdk/build.gradle.kts, publisher-sdk/config.groovy, publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java, publisher-sdk/src/main/java/com/criteo/publisher/csm/CsmBidLifecycleListener.java, publisher-sdk/src/main/java/com/criteo/publisher/csm/Metric.java, publisher-sdk/src/main/java/com/criteo/publisher/csm/MetricSendingQueueConsumer.java, publisher-sdk/src/main/java/com/criteo/publisher/csm/MetricSendingTask.kt, publisher-sdk/src/main/java/com/criteo/publisher/integration/IntegrationRegistry.kt, publisher-sdk/src/main/java/com/criteo/publisher/model/CdbRequestFactory.java, publisher-sdk/src/main/java/com/criteo/publisher/model/RemoteConfigRequestFactory.java, publisher-sdk/src/main/java/com/criteo/publisher/util/BuildConfigWrapper.java, publisher-sdk/src/test/java/com/criteo/publisher/csm/CsmBidLifecycleListenerTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/csm/MetricSendingQueueConsumerTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/model/CdbRequestFactoryTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/model/RemoteConfigRequestFactoryTest.kt
=> Use integration registry instead of const profile ID

publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java, publisher-sdk/src/main/java/com/criteo/publisher/csm/CsmBidLifecycleListener.java, publisher-sdk/src/main/java/com/criteo/publisher/model/CdbRequest.java, publisher-sdk/src/main/java/com/criteo/publisher/model/CdbRequestFactory.java, publisher-sdk/src/test/java/com/criteo/publisher/csm/CsmBidLifecycleListenerTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/model/CdbRequestFactoryTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/model/CdbRequestTest.kt
In order to join CSM and bidding, the request group ID should be
sent to CDB, hence it is generated prior the bid request and not after.
JIRA: EE-1111
=> Send the requestGroupId field in the bid request

publisher-sdk-tests/src/androidTest/java/com/criteo/publisher/csm/FileMetricRepositoryTest.java
This test had failed because there was two metrics read. This means that
the read task occurred after the second update task. This was guarded
via a sleep that is not deterministic, hence the flakyness.
This fix this flakyness by forcing the execution: second update is
blocked until read is finished.
=> Remove sleep in test to reduce flakyness

.detekt/config.yml, .detekt/license.template, app/build.gradle.kts, app/src/main/java/com/criteo/testapp/StandaloneRecyclerViewActivity.kt, buildSrc/src/main/java/AndroidModule.kt, buildSrc/src/main/java/Deps.kt, publisher-sdk-tests/build.gradle.kts, publisher-sdk/build.gradle.kts, publisher-sdk/src/main/java/com/criteo/publisher/integration/IntegrationDetector.kt, test-utils/build.gradle.kts, test-utils/src/main/java/com/criteo/publisher/mock/CdbMock.kt
The target is to restrain coding style to have a homogeneous code base.
Also, code smell are detected to avoid potential bugs.
JIRA: EE-1214
=> Activate custom rules on Detekt

.github/workflows/main.yml, README.md, build.gradle.kts
Complete the information given to Sonar to enrich produced reports:
JIRA: EE-1214
=> Complete sonar reports

CHANGELOG.md, app/src/main/java/com/criteo/testapp/InHouseActivity.java, app/src/main/java/com/criteo/testapp/StandaloneActivity.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/degraded/StandaloneDegradedTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/InHouseFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/ProfileIdFunctionalTest.kt, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/StandaloneFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/manual/StandaloneInterstitialManualTest.java, publisher-sdk/src/main/java/com/criteo/publisher/CriteoInterstitial.java
=> Remove context parameter from CriteoInterstitial

test-utils/build.gradle.kts, test-utils/src/androidTest/java/com/criteo/publisher/concurrent/ThreadingUtilAndroidTest.kt, test-utils/src/main/java/com/criteo/publisher/concurrent/ThreadingUtil.java, test-utils/src/test/java/com/criteo/publisher/concurrent/ThreadingUtilTest.kt
Sonar is detecting major bugs in the code base. This is why we currently have a C note as reliability.
https://sonarcloud.io/project/issues?id=com.criteo.publisher%3Acriteo-publisher-sdk&resolved=false&severities=MAJOR&types=BUG
=> Fix interrupted exception handling

app/src/main/java/com/criteo/testapp/SplashActivity.java, app/src/main/res/layout/content_splash.xml, app/src/main/res/values/strings.xml
Additionally, flatten the splash screen layout using a ConstraintLayout.
=> Update the version dynamically on test-app

publisher-sdk/config.groovy, publisher-sdk/src/androidTest/java/com/criteo/publisher/BidManagerFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/StandaloneFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/model/ConfigIntegrationTests.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/network/PubSdkApiIntegrationTest.java, publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java, publisher-sdk/src/main/java/com/criteo/publisher/model/Config.java, publisher-sdk/src/main/java/com/criteo/publisher/model/RemoteConfigRequest.java, publisher-sdk/src/main/java/com/criteo/publisher/model/RemoteConfigRequestFactory.java, publisher-sdk/src/main/java/com/criteo/publisher/model/RemoteConfigResponse.java, publisher-sdk/src/main/java/com/criteo/publisher/network/LiveBidRequestSender.kt, publisher-sdk/src/test/java/com/criteo/publisher/model/ConfigTest.java, publisher-sdk/src/test/java/com/criteo/publisher/model/RemoteConfigRequestFactoryTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/model/RemoteConfigRequestTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/model/RemoteConfigResponseTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/network/LiveBidRequestSenderTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/network/PubSdkApiTest.java, test-utils/src/main/java/com/criteo/publisher/mock/CdbMock.kt
=> Use time budget from CaC rather than hard coded one

publisher-sdk/src/main/java/com/criteo/publisher/LiveCdbCallListener.java, publisher-sdk/src/main/java/com/criteo/publisher/csm/CsmBidLifecycleListener.java, publisher-sdk/src/test/java/com/criteo/publisher/csm/CsmBidLifecycleListenerTest.kt
`readyToSend` was mistakenly set to `true` instead of `cachedBidUsed`
=> Set cachedBidUsed on CsmLifecycleListener#onCachedBid

CHANGELOG.md, publisher-sdk/src/androidTest/java/com/criteo/publisher/csm/CsmFunctionalTest.java, publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java, publisher-sdk/src/main/java/com/criteo/publisher/csm/CsmBidLifecycleListener.java, publisher-sdk/src/main/java/com/criteo/publisher/privacy/Tcf2CsmGuard.kt, publisher-sdk/src/main/java/com/criteo/publisher/privacy/UserPrivacyUtil.java, publisher-sdk/src/main/java/com/criteo/publisher/privacy/gdpr/GdprDataFetcher.java, publisher-sdk/src/main/java/com/criteo/publisher/util/SafeSharedPreferences.java, publisher-sdk/src/main/java/com/criteo/publisher/util/SafeSharedPreferencesExt.kt, publisher-sdk/src/test/java/com/criteo/publisher/csm/CsmBidLifecycleListenerTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/privacy/Tcf2CsmGuardTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/privacy/UserPrivacyUtilTest.java, test-utils/build.gradle.kts, test-utils/src/androidTest/java/com/criteo/publisher/mock/DependenciesAnnotationInjectionAndroidTest.kt, test-utils/src/androidTest/java/com/criteo/publisher/mock/JavaDummyDependencyProvider.java, test-utils/src/main/java/com/criteo/publisher/mock/DependenciesAnnotationInjection.java
=> Do not store technical metrics unless TCF consent is given

CHANGELOG.md, app/src/main/java/com/criteo/testapp/PubSdkDemoApplication.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/CriteoFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/model/ConfigIntegrationTests.java, publisher-sdk/src/main/java/com/criteo/publisher/Criteo.java, publisher-sdk/src/main/java/com/criteo/publisher/model/Config.java, publisher-sdk/src/test/java/com/criteo/publisher/model/ConfigTest.java, test-utils/src/main/java/com/criteo/publisher/CriteoUtil.java
=> Remove deprecated code

app/src/main/java/com/criteo/testapp/InHouseActivity.java, publisher-sdk-tests/src/main/java/com/criteo/publisher/activity/TestNativeActivity.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/CriteoBannerEventControllerTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/CriteoBannerViewIntegrationTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/CriteoInterstitialEventControllerIntegrationTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/CriteoInterstitialIntegrationTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/advancednative/AdvancedNativeFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/csm/CsmFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/degraded/InHouseDegradedTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/InHouseFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/ProfileIdFunctionalTest.kt, publisher-sdk/src/androidTest/java/com/criteo/publisher/privacy/gdpr/GdprTcfEndToEndWithCdbTests.java, publisher-sdk/src/main/java/com/criteo/publisher/Bid.java, publisher-sdk/src/main/java/com/criteo/publisher/BidResponseListener.java, publisher-sdk/src/main/java/com/criteo/publisher/Criteo.java, publisher-sdk/src/main/java/com/criteo/publisher/CriteoBannerEventController.java, publisher-sdk/src/main/java/com/criteo/publisher/CriteoBannerView.java, publisher-sdk/src/main/java/com/criteo/publisher/CriteoInternal.java, publisher-sdk/src/main/java/com/criteo/publisher/CriteoInterstitial.java, publisher-sdk/src/main/java/com/criteo/publisher/CriteoInterstitialEventController.java, publisher-sdk/src/main/java/com/criteo/publisher/DummyCriteo.java, publisher-sdk/src/main/java/com/criteo/publisher/InHouse.java, publisher-sdk/src/main/java/com/criteo/publisher/advancednative/CriteoNativeLoader.java, publisher-sdk/src/test/java/com/criteo/publisher/BidTest.java, publisher-sdk/src/test/java/com/criteo/publisher/CriteoBannerViewTest.java, publisher-sdk/src/test/java/com/criteo/publisher/CriteoInternalUnitTest.java, publisher-sdk/src/test/java/com/criteo/publisher/CriteoInterstitialTest.java, publisher-sdk/src/test/java/com/criteo/publisher/DummyCriteoTest.java, publisher-sdk/src/test/java/com/criteo/publisher/InHouseTest.java, publisher-sdk/src/test/java/com/criteo/publisher/advancednative/CriteoNativeLoaderTest.kt
=> Use live bidding with InHouse

publisher-sdk/src/androidTest/java/com/criteo/publisher/network/PubSdkApiIntegrationTest.java, publisher-sdk/src/main/java/com/criteo/publisher/model/Config.java, publisher-sdk/src/test/java/com/criteo/publisher/model/ConfigTest.java, test-utils/src/main/java/com/criteo/publisher/mock/CdbMock.kt
=> Update default value of time budget

publisher-sdk/src/androidTest/java/com/criteo/publisher/BidManagerFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/DfpHeaderBiddingFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/InHouseFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/MoPubHeaderBiddingFunctionalTest.java, publisher-sdk/src/main/java/com/criteo/publisher/BidManager.java, publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java, publisher-sdk/src/main/java/com/criteo/publisher/network/BidRequestSender.java, publisher-sdk/src/main/java/com/criteo/publisher/network/CdbCall.java, publisher-sdk/src/main/java/com/criteo/publisher/network/LiveBidRequestSender.kt, publisher-sdk/src/test/java/com/criteo/publisher/network/BidRequestSenderTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/network/LiveBidRequestSenderTest.kt
=> Add functional tests on InHouse + AppBidding

publisher-sdk/src/androidTest/java/com/criteo/publisher/BidManagerFunctionalTest.java, publisher-sdk/src/main/java/com/criteo/publisher/BidManager.java, publisher-sdk/src/main/java/com/criteo/publisher/LiveCdbCallListener.java, publisher-sdk/src/main/java/com/criteo/publisher/cache/SdkCache.java, publisher-sdk/src/main/java/com/criteo/publisher/model/CdbResponseSlot.kt, publisher-sdk/src/test/java/com/criteo/publisher/LiveCdbCallListenerTests.kt, publisher-sdk/src/test/java/com/criteo/publisher/advancednative/CriteoNativeLoaderTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/model/CdbResponseSlotTest.java
=> [LiveBidding] Add functional tests on BidManager

publisher-sdk/src/androidTest/java/com/criteo/publisher/BearcatFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/BearcatPrivacyFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/BidManagerFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/UserPrivacyFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/csm/CsmFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/CriteoFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/model/ConfigIntegrationTests.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/network/AdvertisingInfoFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/network/PubSdkApiIntegrationTest.java, publisher-sdk/src/main/java/com/criteo/publisher/BidManager.java, publisher-sdk/src/main/java/com/criteo/publisher/model/Config.java, publisher-sdk/src/main/java/com/criteo/publisher/model/RemoteConfigResponse.java, publisher-sdk/src/test/java/com/criteo/publisher/model/ConfigTest.java, publisher-sdk/src/test/java/com/criteo/publisher/model/RemoteConfigResponseTest.kt, test-utils/src/main/java/com/criteo/publisher/mock/CdbMock.kt, test-utils/src/main/java/com/criteo/publisher/mock/MockedDependenciesRule.java
=> Use CaC to enable/disable prefetch

CHANGELOG.md
=> Update changelog for v4.0.0

app/src/main/java/com/criteo/testapp/BiConsumer.java, app/src/main/java/com/criteo/testapp/DfpActivity.java, app/src/main/java/com/criteo/testapp/InHouseActivity.java, app/src/main/java/com/criteo/testapp/MopubActivity.java, app/src/main/java/com/criteo/testapp/PubSdkDemoApplication.java, app/src/main/java/com/criteo/testapp/StandaloneActivity.java, app/src/main/java/com/criteo/testapp/StandaloneRecyclerViewActivity.kt, app/src/main/java/com/criteo/testapp/integration/IntegrationSelectorActivity.kt, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/ProfileIdFunctionalTest.kt, publisher-sdk/src/main/java/com/criteo/publisher/BidResponseListener.java, publisher-sdk/src/main/java/com/criteo/publisher/ConsumableBidLoader.java, publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java, publisher-sdk/src/main/java/com/criteo/publisher/LiveCdbCallListener.java, publisher-sdk/src/test/java/com/criteo/publisher/ConsumableBidLoaderTest.java, publisher-sdk/src/test/java/com/criteo/publisher/advancednative/CriteoNativeLoaderTest.kt, test-utils/src/main/java/com/criteo/publisher/mock/MockedDependenciesRule.java
=> Fix memory retention in test app

CHANGELOG.md, app/src/main/java/com/criteo/testapp/StandaloneRecyclerViewActivity.kt, app/src/main/java/com/criteo/testapp/listener/TestAppBannerAdListener.java, app/src/main/java/com/criteo/testapp/listener/TestAppNativeAdListener.java, publisher-sdk-tests/src/main/java/com/criteo/publisher/activity/TestNativeActivity.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/StandaloneFunctionalTest.java, publisher-sdk/src/main/java/com/criteo/publisher/CriteoAdListener.java, publisher-sdk/src/main/java/com/criteo/publisher/CriteoBannerAdListener.java, publisher-sdk/src/main/java/com/criteo/publisher/CriteoBannerEventController.java, publisher-sdk/src/main/java/com/criteo/publisher/CriteoInterstitialAdListener.java, publisher-sdk/src/main/java/com/criteo/publisher/advancednative/ClickHelper.java, publisher-sdk/src/main/java/com/criteo/publisher/advancednative/CriteoNativeAdListener.java, publisher-sdk/src/main/java/com/criteo/publisher/advancednative/ImpressionHelper.java, publisher-sdk/src/main/java/com/criteo/publisher/tasks/CriteoBannerListenerCallTask.java, publisher-sdk/src/test/java/com/criteo/publisher/tasks/CriteoBannerListenerCallTaskTest.java
=> Refactor banner listener

app/build.gradle.kts, app/src/main/java/com/criteo/testapp/MopubMediationActivity.java
=> Revert "Remove mediation adapters from test app"

publisher-sdk/src/staging/AndroidManifest.xml, publisher-sdk/src/staging/res/xml/network_security_config.xml
This allows to spy/mock network via Charles Proxy
=> Trust user's certificates for staging artifacts

publisher-sdk/src/androidTest/java/com/criteo/publisher/SessionTest.kt, publisher-sdk/src/androidTest/java/com/criteo/publisher/context/ConnectionTypeFetcherTest.kt, publisher-sdk/src/androidTest/java/com/criteo/publisher/context/ContextProviderTest.kt, publisher-sdk/src/main/AndroidManifest.xml, publisher-sdk/src/main/java/com/criteo/publisher/CriteoInternal.java, publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java, publisher-sdk/src/main/java/com/criteo/publisher/Session.kt, publisher-sdk/src/main/java/com/criteo/publisher/context/ConnectionTypeFetcher.kt, publisher-sdk/src/main/java/com/criteo/publisher/context/ContextProvider.kt, publisher-sdk/src/main/java/com/criteo/publisher/util/MapUtil.kt, test-utils/src/main/java/com/criteo/publisher/mock/DependenciesAnnotationInjection.java, test-utils/src/test/java/com/criteo/publisher/mock/DependenciesAnnotationInjectionTest.kt
=> Implement signals that can be collected automatically

CHANGELOG.md, app/src/main/java/com/criteo/testapp/InHouseActivity.java, publisher-sdk-tests/src/main/java/com/criteo/publisher/activity/TestNativeActivity.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/ProfileIdFunctionalTest.kt, publisher-sdk/src/main/java/com/criteo/publisher/advancednative/CriteoNativeLoader.java
=> Allow CriteoNativeLoader to initialize without AdUnit

app/src/main/java/com/criteo/testapp/PubSdkDemoApplication.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/context/EmailHasherTest.kt, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/CriteoFunctionalTest.java, publisher-sdk/src/main/java/com/criteo/publisher/Criteo.java, publisher-sdk/src/main/java/com/criteo/publisher/CriteoInternal.java, publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java, publisher-sdk/src/main/java/com/criteo/publisher/DummyCriteo.java, publisher-sdk/src/main/java/com/criteo/publisher/context/AbstractContextData.java, publisher-sdk/src/main/java/com/criteo/publisher/context/EmailHasher.kt, publisher-sdk/src/main/java/com/criteo/publisher/context/UserData.java, publisher-sdk/src/main/java/com/criteo/publisher/context/UserDataHolder.kt, publisher-sdk/src/test/java/com/criteo/publisher/context/UserDataTest.kt
=> Implement public API collecting UserData from publisher

build.gradle.kts
This allows to reactive quality checks in the CI pipeline.
JIRA: EE-1335
=> Deactivate declaration of JUnit report to Sonar

publisher-sdk/src/androidTest/java/com/criteo/publisher/BidManagerFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/context/ContextFunctionalTest.kt, publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java, publisher-sdk/src/main/java/com/criteo/publisher/context/AbstractContextData.java, publisher-sdk/src/main/java/com/criteo/publisher/context/ContextProvider.kt, publisher-sdk/src/main/java/com/criteo/publisher/context/ContextUtil.kt, publisher-sdk/src/main/java/com/criteo/publisher/model/CdbRequestFactory.java, publisher-sdk/src/main/java/com/criteo/publisher/model/CdbRequestSlot.java, publisher-sdk/src/main/java/com/criteo/publisher/model/Publisher.java, publisher-sdk/src/main/java/com/criteo/publisher/model/RemoteConfigRequestFactory.java, publisher-sdk/src/main/java/com/criteo/publisher/model/User.java, publisher-sdk/src/main/java/com/criteo/publisher/network/PubSdkApi.java, publisher-sdk/src/main/java/com/criteo/publisher/privacy/gdpr/GdprData.java, publisher-sdk/src/test/java/com/criteo/publisher/DependencyProviderTest.java, publisher-sdk/src/test/java/com/criteo/publisher/model/CdbRequestFactoryTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/model/CdbRequestSlotTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/model/CdbRequestTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/model/RemoteConfigRequestFactoryTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/model/UserTest.java, publisher-sdk/src/test/java/com/criteo/publisher/network/PubSdkApiTest.java, publisher-sdk/src/test/java/com/criteo/publisher/privacy/gdpr/GdprDataFactoryTest.kt
=> Merge contexts and put them in CDB request

app/src/main/AndroidManifest.xml, publisher-sdk/src/androidTest/java/com/criteo/publisher/context/ConnectionTypeFetcherTest.kt, publisher-sdk/src/main/java/com/criteo/publisher/context/ConnectionTypeFetcher.kt
=> Use READ_PHONE_STATE to get contype if permission is already granted

buildSrc/src/main/java/Deps.kt, publisher-sdk/src/androidTest/java/com/criteo/publisher/advancednative/CriteoImageLoaderTest.java
This version of picasso supports AndroidX.
=> Update picasso to 2.8

publisher-sdk/src/androidTest/java/com/criteo/publisher/BidManagerFunctionalTest.java, publisher-sdk/src/main/java/com/criteo/publisher/model/CdbResponseSlot.kt, publisher-sdk/src/test/java/com/criteo/publisher/model/CdbResponseSlotTest.java
=> Fix caching of silent bid

CHANGELOG.md, app/src/main/java/com/criteo/testapp/PubSdkDemoApplication.java, publisher-sdk/build.gradle.kts, publisher-sdk/config.groovy, publisher-sdk/src/androidTest/java/com/criteo/publisher/logging/DebugLoggingFunctionalTest.kt, publisher-sdk/src/main/java/com/criteo/publisher/Criteo.java, publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java, publisher-sdk/src/main/java/com/criteo/publisher/logging/ConsoleHandler.kt, publisher-sdk/src/main/java/com/criteo/publisher/logging/Logger.java, publisher-sdk/src/main/java/com/criteo/publisher/logging/LoggerFactory.java, publisher-sdk/src/main/java/com/criteo/publisher/util/BuildConfigWrapper.java, publisher-sdk/src/test/java/com/criteo/publisher/logging/ConsoleHandlerTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/logging/LoggerTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/mock/MockedDependenciesRuleLoggingTest.kt, test-utils/src/main/java/com/criteo/publisher/mock/MockedDependenciesRule.java
=> Add public API to enable "debug" logs of Console handler

.github/workflows/main.yml, .github/workflows/release.yml
=> Fix CI Fix deprecations

publisher-sdk/build.gradle.kts, publisher-sdk/config.groovy, publisher-sdk/src/androidTest/java/com/criteo/publisher/BidManagerFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/logging/RemoteLoggingFunctionalTest.kt, publisher-sdk/src/androidTest/java/com/criteo/publisher/network/PubSdkApiIntegrationTest.java, publisher-sdk/src/main/java/com/criteo/publisher/BidManager.java, publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java, publisher-sdk/src/main/java/com/criteo/publisher/bid/LoggingBidLifecycleListener.java, publisher-sdk/src/main/java/com/criteo/publisher/logging/RemoteHandler.kt, publisher-sdk/src/main/java/com/criteo/publisher/logging/RemoteLogSendingQueueConsumer.kt, publisher-sdk/src/main/java/com/criteo/publisher/network/PubSdkApi.java, publisher-sdk/src/main/java/com/criteo/publisher/util/BuildConfigWrapper.java, publisher-sdk/src/test/java/com/criteo/publisher/logging/RemoteHandlerTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/logging/RemoteLogSendingQueueConsumerTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/network/PubSdkApiTest.java, test-utils/src/main/java/com/criteo/publisher/network/CdbMock.kt
=> Remote Handler: Implement sending of logs to CDB

publisher-sdk/src/androidTest/java/com/criteo/publisher/logging/PublisherCodeRemoverTest.kt, publisher-sdk/src/androidTest/java/com/criteo/publisher/logging/RemoteLoggingFunctionalTest.kt, publisher-sdk/src/androidTest/java/com/dummypublisher/DummyPublisherCode.kt, publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java, publisher-sdk/src/main/java/com/criteo/publisher/logging/PublisherCodeRemover.kt, publisher-sdk/src/main/java/com/criteo/publisher/logging/RemoteLogRecordsFactory.kt, publisher-sdk/src/main/java/com/criteo/publisher/logging/RemoteLogSendingQueue.kt, publisher-sdk/src/test/java/com/criteo/publisher/logging/PublisherCodeRemoverJvmTest.kt, test-utils/src/main/java/com/criteo/publisher/util/ThrowableExt.kt
=> Hide exception/stacktrace coming from publisher code

publisher-sdk/src/androidTest/java/com/criteo/publisher/network/PubSdkApiIntegrationTest.java, publisher-sdk/src/main/java/com/criteo/publisher/BiddingLogMessage.kt, publisher-sdk/src/main/java/com/criteo/publisher/ErrorLogMessage.kt, publisher-sdk/src/main/java/com/criteo/publisher/SdkInitLogMessage.kt, publisher-sdk/src/main/java/com/criteo/publisher/csm/SendingQueueLogMessage.kt, publisher-sdk/src/main/java/com/criteo/publisher/headerbidding/AppBiddingLogMessage.kt, publisher-sdk/src/main/java/com/criteo/publisher/interstitial/InterstitialLogMessage.kt, publisher-sdk/src/main/java/com/criteo/publisher/logging/LogMessage.kt, publisher-sdk/src/main/java/com/criteo/publisher/logging/Logger.java, publisher-sdk/src/main/java/com/criteo/publisher/logging/RemoteLogRecords.kt, publisher-sdk/src/main/java/com/criteo/publisher/logging/RemoteLogRecordsFactory.kt, publisher-sdk/src/test/java/com/criteo/publisher/logging/RemoteLogRecordsFactoryTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/logging/RemoteLogRecordsTest.kt
=> Use log id field to identify logs

CHANGELOG.md, buildSrc/src/main/java/SdkVersion.kt, publisher-sdk/src/main/java/com/criteo/publisher/ErrorLogMessage.kt, publisher-sdk/src/main/java/com/criteo/publisher/SafeRunnable.java, publisher-sdk/src/main/java/com/criteo/publisher/logging/PublisherCodeRemover.kt, publisher-sdk/src/test/java/com/criteo/publisher/SafeRunnableTest.kt
* UnknownHostException are not treated as error
* libcore packages are considered as framework packages which does not belong to publishers.
=> Fix minor issues with remote log

publisher-sdk/src/main/java/com/criteo/publisher/model/RemoteConfigRequest.java, publisher-sdk/src/test/java/com/criteo/publisher/model/RemoteConfigRequestTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/network/PubSdkApiTest.java
=> Provide OS (android) to remote configuration

publisher-sdk/src/main/java/com/criteo/publisher/logging/RemoteLogRecords.kt, publisher-sdk/src/main/java/com/criteo/publisher/logging/RemoteLogRecordsFactory.kt, publisher-sdk/src/test/java/com/criteo/publisher/logging/RemoteLogRecordsFactoryTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/logging/RemoteLogRecordsTest.kt
=> Add deviceOs in remote log request

CHANGELOG.md, buildSrc/src/main/java/AndroidModule.kt
=> Support Android 11 (API level 30)

.github/workflows/main.yml, .github/workflows/release.yml, CHANGELOG.md, app/build.gradle.kts, build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/java/Extensions.kt, buildSrc/src/main/java/Publications.kt, buildSrc/src/main/java/Repositories.kt, buildSrc/src/main/java/Slack.kt, publisher-sdk/build.gradle.kts, publisher-sdk/src/main/java/com/criteo/publisher/context/UserData.java, test-utils/build.gradle.kts
=> Deploy artifacts on Maven Central

buildSrc/src/main/java/Repositories.kt, buildSrc/src/main/java/Slack.kt
=> Stop using JCenter to fetch mediation adapters

CHANGELOG.md, app/src/main/java/com/criteo/testapp/DfpActivity.java, app/src/main/java/com/criteo/testapp/MopubActivity.java, app/src/main/java/com/criteo/testapp/PubSdkDemoApplication.java, app/src/main/res/layout/content_dfp.xml, app/src/main/res/layout/content_mopub.xml, app/src/main/res/values/strings.xml, publisher-sdk/src/androidTest/java/com/criteo/publisher/headerbidding/MoPubHeaderBiddingTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/DfpHeaderBiddingFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/MoPubHeaderBiddingFunctionalTest.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/logging/RemoteLoggingFunctionalTest.kt, publisher-sdk/src/androidTest/java/com/criteo/publisher/network/PubSdkApiIntegrationTest.java, publisher-sdk/src/main/java/com/criteo/publisher/headerbidding/DfpHeaderBidding.java, publisher-sdk/src/main/java/com/criteo/publisher/headerbidding/MoPubHeaderBidding.java, publisher-sdk/src/main/java/com/criteo/publisher/model/CdbResponseSlot.kt, publisher-sdk/src/test/java/com/criteo/publisher/model/CdbResponseSlotTest.java, test-utils/src/main/java/com/criteo/publisher/StubConstants.java, test-utils/src/main/java/com/criteo/publisher/TestAdUnits.java, test-utils/src/main/java/com/criteo/publisher/headerbidding/AbstractDfpHeaderBiddingTest.java, test-utils/src/main/java/com/criteo/publisher/network/CdbMock.kt
=> Support VAST video support for GAM and MoPub AppBidding

.github/workflows/main.yml, CHANGELOG.md, buildSrc/src/main/java/AndroidModule.kt
=> ⬆️ Add support for Android 12L (API 32)

buildSrc/src/main/java/Deps.kt, publisher-sdk/src/androidTest/java/com/criteo/publisher/adview/AdWebViewClientTest.kt, publisher-sdk/src/androidTest/java/com/criteo/publisher/adview/AdWebViewTest.kt, publisher-sdk/src/androidTest/java/com/criteo/publisher/adview/MraidIntegrationTest.kt, publisher-sdk/src/androidTest/java/com/criteo/publisher/adview/TestAdWebViewClient.kt, publisher-sdk/src/main/java/com/criteo/publisher/CriteoBannerView.java, publisher-sdk/src/main/java/com/criteo/publisher/CriteoInterstitialActivity.java, publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java, publisher-sdk/src/main/java/com/criteo/publisher/adview/AdWebView.kt, publisher-sdk/src/main/java/com/criteo/publisher/adview/AdWebViewClient.kt, publisher-sdk/src/main/java/com/criteo/publisher/adview/AdWebViewClientListener.kt, publisher-sdk/src/main/java/com/criteo/publisher/adview/MraidInteractor.kt, publisher-sdk/src/main/java/com/criteo/publisher/csm/MetricRequest.kt, publisher-sdk/src/test/java/com/criteo/publisher/adview/MraidInteractorTest.kt, test-utils/src/main/java/com/criteo/publisher/MraidUtil.kt
- Report MRAID readiness
- Add ability to report error on MRAID object from SDK
JIRA: DPP-4237
=> 💪 Add SDK report about MRAID readiness

publisher-sdk/src/androidTest/java/com/criteo/publisher/integration/MraidBannerFunctionalTest.kt, publisher-sdk/src/androidTest/java/com/criteo/publisher/model/ConfigIntegrationTests.java, publisher-sdk/src/androidTest/java/com/criteo/publisher/network/PubSdkApiIntegrationTest.java, publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java, publisher-sdk/src/main/java/com/criteo/publisher/model/Config.java, publisher-sdk/src/main/java/com/criteo/publisher/model/RemoteConfigResponse.kt, publisher-sdk/src/test/java/com/criteo/publisher/DependencyProviderTest.java, publisher-sdk/src/test/java/com/criteo/publisher/model/ConfigTest.java, publisher-sdk/src/test/java/com/criteo/publisher/model/RemoteConfigResponseTest.kt, test-utils/src/main/java/com/criteo/publisher/network/CdbMock.kt
=> 🚩 Add feature flag for mraid

publisher-sdk/src/main/java/com/criteo/publisher/DependencyProvider.java, publisher-sdk/src/main/java/com/criteo/publisher/model/ApiFramework.kt, publisher-sdk/src/main/java/com/criteo/publisher/model/CdbRequestFactory.java, publisher-sdk/src/main/java/com/criteo/publisher/model/CdbRequestSlot.kt, publisher-sdk/src/test/java/com/criteo/publisher/model/CdbRequestFactoryTest.kt, publisher-sdk/src/test/java/com/criteo/publisher/model/CdbRequestSlotTest.kt
=> ❔ Send SDK Mraid capability in bid request
